//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _Диплом.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Автомобиль
    {
        public int CarID { get; set; }
        public string Марка { get; set; }
        public string РегистрационныйНомер { get; set; }
        public int ТипАвтомобиля { get; set; }
        public int ТипТоплива { get; set; }
    
        public virtual ТипАвтомобиля ТипАвтомобиля1 { get; set; }
        public virtual ТипТоплива ТипТоплива1 { get; set; }
    }
}
