//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _Диплом.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Прицеп
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Прицеп()
        {
            this.ПутевойЛист = new HashSet<ПутевойЛист>();
        }
    
        public int TrailerID { get; set; }
        public string Марка { get; set; }
        public string РегистрационныйНомер { get; set; }
        public int ГаражныйНомер { get; set; }
        public int ТипПрицепа { get; set; }
    
        public virtual ТипПрицепа ТипПрицепа1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПутевойЛист> ПутевойЛист { get; set; }
    }
}
