//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _Диплом.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПутевойЛист
    {
        public int ListID { get; set; }
        public int UserID { get; set; }
        public int CarID { get; set; }
        public Nullable<int> TrailerID { get; set; }
        public int ZakazchikID { get; set; }
        public System.DateTime ВыездИзГаражаПоГрафику { get; set; }
        public System.DateTime ВыездИзГаражаФактический { get; set; }
        public int НулевойПробегДоВыезда { get; set; }
        public int ПоказаниеСпидометраДоВыезда { get; set; }
        public int ВыданоГорючего { get; set; }
        public int ОстатокГорючегоПриВыезде { get; set; }
        public string АдресПунктаПогрузки { get; set; }
        public string АдресПунктаРазгрузки { get; set; }
        public int ProductID { get; set; }
        public int Расстояние { get; set; }
        public int ТипПутевогоЛиста { get; set; }
    
        public virtual Заказчик Заказчик { get; set; }
        public virtual Пользователь Пользователь { get; set; }
        public virtual Прицеп Прицеп { get; set; }
        public virtual Продукт Продукт { get; set; }
        public virtual ТипПутевогоЛиста ТипПутевогоЛиста1 { get; set; }
    }
}
